apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: educenter-os
type: Opaque
stringData:
  POSTGRES_DB: educenter
  POSTGRES_USER: educenter_user
  POSTGRES_PASSWORD: educenter_password